import '../models/models.dart';
import 'constants.dart';

class DummyData {
  static final List<UserModel> providers = [
    UserModel(
      id: 'p1',
      fullName: 'Ahmad Karimi',
      email: 'ahmad@example.com',
      phone: '0501234567',
      city: 'Nazareth',
      role: UserRole.professional,
      workArea: 'north_country',
      experienceYears: 10,
      specialty: 'electrician',
      serviceDescription: 'Experienced in residential and commercial electrical installation and maintenance',
      rating: 4.8,
      services: ['Electrical Installation', 'Maintenance', 'LED Lighting', 'Electrical Panels'],
      servicesList: [
        ServiceModel(id: 's1', name: 'Electrical Installation', description: 'Installing and connecting wires and electrical extensions', price: 350),
        ServiceModel(id: 's2', name: 'Electrical Maintenance', description: 'Repairing and maintaining electrical faults', price: 200),
        ServiceModel(id: 's3', name: 'LED Lighting', description: 'Installing energy-efficient LED lighting systems', price: 150),
        ServiceModel(id: 's4', name: 'Electrical Panels', description: 'Installing and maintaining main electrical panels', price: 500),
      ],
      languages: ['English', 'Arabic', 'Hebrew'],
    ),
    UserModel(
      id: 'p2',
      fullName: 'Mohammed Hasan',
      email: 'mohammad@example.com',
      phone: '0509876543',
      city: 'Haifa',
      role: UserRole.professional,
      workArea: 'north_country',
      experienceYears: 7,
      specialty: 'carpenter',
      serviceDescription: 'Manufacturing and installing wooden furniture and kitchens',
      rating: 4.6,
      services: ['Kitchens', 'Furniture', 'Doors', 'Windows'],
      servicesList: [
        ServiceModel(id: 's5', name: 'Wooden Kitchens', description: 'Designing and manufacturing custom wooden kitchens', price: 2000),
        ServiceModel(id: 's6', name: 'Furniture', description: 'Manufacturing various wooden furniture pieces', price: 800),
        ServiceModel(id: 's7', name: 'Doors', description: 'Installing and maintaining wooden doors', price: 300),
      ],
      languages: ['English', 'Arabic'],
    ),
    UserModel(
      id: 'p3',
      fullName: 'Khaled Nasser',
      email: 'khaled@example.com',
      phone: '0521234567',
      city: 'Akka',
      role: UserRole.professional,
      workArea: 'north_country',
      experienceYears: 15,
      specialty: 'plumber',
      serviceDescription: 'Expert in all plumbing and sewage work',
      rating: 4.9,
      services: ['Plumbing', 'Sewage', 'Water Heaters', 'Water Filters'],
      servicesList: [
        ServiceModel(id: 's8', name: 'General Plumbing', description: 'Repairing and installing water networks', price: 180),
        ServiceModel(id: 's9', name: 'Sewage & Drainage', description: 'Cleaning and maintaining drainage networks', price: 250),
        ServiceModel(id: 's10', name: 'Water Heater Installation', description: 'Installing and maintaining water heaters', price: 300),
      ],
    ),
    UserModel(
      id: 'p4',
      fullName: 'Yousef Mansour',
      email: 'youssef@example.com',
      phone: '0534567890',
      city: 'Nazareth',
      role: UserRole.professional,
      workArea: 'north_country',
      experienceYears: 5,
      specialty: 'painter',
      serviceDescription: 'Interior and exterior painting at the highest quality',
      rating: 4.5,
      services: ['Interior Painting', 'Exterior Painting', 'Wallpaper', 'Decoration'],
      servicesList: [
        ServiceModel(id: 's11', name: 'Interior Painting', description: 'Painting rooms and halls in various colors', price: 400),
        ServiceModel(id: 's12', name: 'Exterior Painting', description: 'Painting facades and entrances', price: 600),
        ServiceModel(id: 's13', name: 'Wallpaper', description: 'Installing decorative wallpaper', price: 350),
      ],
    ),
    UserModel(
      id: 'p5',
      fullName: 'United Construction Co.',
      email: 'build@example.com',
      phone: '0545678901',
      city: 'Tiberias',
      role: UserRole.contractor,
      workArea: 'north_country',
      experienceYears: 20,
      specialty: 'mason',
      serviceDescription: 'General contracting, construction and renovation',
      rating: 4.7,
      services: ['Construction', 'Renovation', 'Finishing', 'Design'],
      servicesList: [
        ServiceModel(id: 's14', name: 'New Construction', description: 'Building houses and buildings from scratch', price: 50000),
        ServiceModel(id: 's15', name: 'Renovation', description: 'Renovating and restoring old buildings', price: 15000),
        ServiceModel(id: 's16', name: 'Interior Finishing', description: 'Interior finishing and decoration works', price: 8000),
      ],
      team: [
        WorkerModel(
          id: 'w1', name: 'Samer Ali', specialty: 'Construction',
          phone: '0541234567', email: 'samer.ali@example.com',
          city: 'Nazareth',
          totalJobs: 45, currentJobs: 2,
          yearsExperience: 8, rating: 4.8,
          skills: ['Masonry', 'Foundations', 'Structural Work', 'Concrete'],
          workHours: 'Sun–Thu, 7:00 AM – 4:00 PM',
          status: WorkerStatus.available,
          description: 'Experienced in construction, structural work, and building from scratch.',
        ),
        WorkerModel(
          id: 'w2', name: 'Fadi Hassan', specialty: 'Finishing',
          phone: '0542345678', email: 'fadi.hassan@example.com',
          city: 'Nazareth',
          totalJobs: 38, currentJobs: 1,
          yearsExperience: 6, rating: 4.6,
          skills: ['Tiling', 'Plastering', 'Painting', 'Drywall'],
          workHours: 'Sun–Fri, 8:00 AM – 5:00 PM',
          status: WorkerStatus.available,
          description: 'Specializes in interior finishing, tiling, and renovation work.',
        ),
        WorkerModel(
          id: 'w3', name: 'Nader Samir', specialty: 'Electrical',
          phone: '0543456789', email: 'nader.samir@example.com',
          city: 'Nazareth',
          totalJobs: 29, currentJobs: 0,
          yearsExperience: 5, rating: 4.7,
          skills: ['Wiring', 'Panels', 'Smart Home', 'Lighting'],
          workHours: 'Sun–Thu, 9:00 AM – 6:00 PM',
          status: WorkerStatus.available,
          description: 'Handles all electrical work on construction sites, wiring and panels.',
        ),
      ],
      languages: ['English', 'Arabic', 'Hebrew'],
    ),
    UserModel(
      id: 'p6',
      fullName: 'Omar Bustani',
      email: 'omar@example.com',
      phone: '0556789012',
      city: 'Kfar Kana',
      role: UserRole.professional,
      workArea: 'nazareth',
      experienceYears: 8,
      specialty: 'gardener',
      serviceDescription: 'Landscape design, planting and irrigation',
      rating: 4.4,
      services: ['Landscaping', 'Lawn Mowing', 'Planting', 'Irrigation Systems'],
      servicesList: [
        ServiceModel(id: 's17', name: 'Garden Design', description: 'Designing and landscaping home gardens', price: 500),
        ServiceModel(id: 's18', name: 'Lawn Mowing', description: 'Mowing and cleaning grass areas', price: 120),
        ServiceModel(id: 's19', name: 'Irrigation Systems', description: 'Installing automatic irrigation systems', price: 800),
      ],
    ),
  ];

  static final List<CategoryModel> categories = AppConstants.allCategories.asMap().entries.map((entry) {
    return CategoryModel(
      id: 'c${entry.key + 1}',
      nameKey: entry.value['key']!,
      icon: entry.value['icon']!,
      providerCount: 5 + entry.key,
    );
  }).toList();

  static final List<ConversationModel> conversations = [
    ConversationModel(
      otherUserId: 'p1',
      otherUserName: 'Ahmad Karimi',
      lastMessage: "I'll be there at 10 AM",
      lastMessageTime: DateTime.now().subtract(const Duration(minutes: 30)),
      unreadCount: 2,
      messages: [
        MessageModel(
          id: 'm1', senderId: 'current_user', receiverId: 'p1',
          text: 'Hello, can you come tomorrow?',
          sentAt: DateTime.now().subtract(const Duration(hours: 1)), isRead: true,
        ),
        MessageModel(
          id: 'm2', senderId: 'p1', receiverId: 'current_user',
          text: "I'll be there at 10 AM",
          sentAt: DateTime.now().subtract(const Duration(minutes: 30)), isRead: false,
        ),
      ],
    ),
    ConversationModel(
      otherUserId: 'p3',
      otherUserName: 'Khaled Nasser',
      lastMessage: 'Issue fixed successfully',
      lastMessageTime: DateTime.now().subtract(const Duration(hours: 2)),
      unreadCount: 0,
      messages: [
        MessageModel(
          id: 'm3', senderId: 'p3', receiverId: 'current_user',
          text: 'Issue fixed successfully',
          sentAt: DateTime.now().subtract(const Duration(hours: 2)), isRead: true,
        ),
      ],
    ),
  ];

  static List<OrderModel> orders = [
    // ── Pending ────────────────────────────────────────────────────────────
    OrderModel(
      id: 'o1',
      customerId: 'current_user',
      customerName: 'Sami Arab',
      providerId: 'p2',
      providerName: 'Mohammed Hasan',
      title: 'Wooden Kitchen Installation',
      description: 'Need a new wooden kitchen installed on the ground floor, approximately 4 meters',
      area: 'Nazareth',
      selectedServiceId: 's5',
      selectedServiceName: 'Wooden Kitchens',
      selectedServicePrice: 2000,
      serviceDate: DateTime.now().add(const Duration(days: 3)),
      status: OrderStatus.pending,
      priority: OrderPriority.normal,
      createdAt: DateTime.now().subtract(const Duration(hours: 5)),
    ),
    OrderModel(
      id: 'o2',
      customerId: 'current_user',
      customerName: 'Sami Arab',
      providerId: 'p4',
      providerName: 'Yousef Mansour',
      title: 'Bedroom Painting',
      description: 'Paint bedroom in off-white with decorative ceiling frames',
      area: 'Nazareth',
      selectedServiceId: 's11',
      selectedServiceName: 'Interior Painting',
      selectedServicePrice: 400,
      serviceDate: DateTime.now().add(const Duration(days: 5)),
      status: OrderStatus.pending,
      priority: OrderPriority.normal,
      createdAt: DateTime.now().subtract(const Duration(hours: 2)),
    ),

    // ── In Progress ────────────────────────────────────────────────────────
    OrderModel(
      id: 'o3',
      customerId: 'current_user',
      customerName: 'Sami Arab',
      providerId: 'p1',
      providerName: 'Ahmad Karimi',
      title: 'Electrical Panel Installation',
      description: 'Install a new main electrical panel and wire connections to the second floor',
      area: 'Nazareth',
      selectedServiceId: 's4',
      selectedServiceName: 'Electrical Panels',
      selectedServicePrice: 500,
      serviceDate: DateTime.now().add(const Duration(days: 1)),
      status: OrderStatus.inProgress,
      priority: OrderPriority.urgent,
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
    ),
    OrderModel(
      id: 'o4',
      customerId: 'current_user',
      customerName: 'Sami Arab',
      providerId: 'p6',
      providerName: 'Omar Bustani',
      title: 'Front Garden Landscaping',
      description: 'Landscaping the front garden with seasonal trees and flowers',
      area: 'Kfar Kana',
      selectedServiceId: 's17',
      selectedServiceName: 'Garden Design',
      selectedServicePrice: 500,
      serviceDate: DateTime.now().add(const Duration(hours: 18)),
      status: OrderStatus.inProgress,
      priority: OrderPriority.normal,
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
    ),

    // ── Completed ──────────────────────────────────────────────────────────
    OrderModel(
      id: 'o5',
      customerId: 'current_user',
      customerName: 'Sami Arab',
      providerId: 'p3',
      providerName: 'Khaled Nasser',
      title: 'Kitchen Leak Repair',
      description: 'Fix water leak under the kitchen sink and replace old pipes',
      area: 'Akka',
      selectedServiceId: 's8',
      selectedServiceName: 'General Plumbing',
      selectedServicePrice: 180,
      serviceDate: DateTime.now().subtract(const Duration(days: 4)),
      status: OrderStatus.completed,
      priority: OrderPriority.normal,
      createdAt: DateTime.now().subtract(const Duration(days: 6)),
    ),
    OrderModel(
      id: 'o6',
      customerId: 'current_user',
      customerName: 'Sami Arab',
      providerId: 'p1',
      providerName: 'Ahmad Karimi',
      title: 'LED Lighting Installation',
      description: 'Install LED lighting in the living room and hallway with dimmer switches',
      area: 'Nazareth',
      selectedServiceId: 's3',
      selectedServiceName: 'LED Lighting',
      selectedServicePrice: 150,
      serviceDate: DateTime.now().subtract(const Duration(days: 10)),
      status: OrderStatus.completed,
      priority: OrderPriority.normal,
      createdAt: DateTime.now().subtract(const Duration(days: 12)),
    ),
    OrderModel(
      id: 'o7',
      customerId: 'current_user',
      customerName: 'Sami Arab',
      providerId: 'p2',
      providerName: 'Mohammed Hasan',
      title: 'Wooden Door Installation',
      description: 'Install 3 interior wooden doors with frames and handles',
      area: 'Haifa',
      selectedServiceId: 's7',
      selectedServiceName: 'Doors',
      selectedServicePrice: 300,
      serviceDate: DateTime.now().subtract(const Duration(days: 20)),
      status: OrderStatus.completed,
      priority: OrderPriority.normal,
      createdAt: DateTime.now().subtract(const Duration(days: 22)),
    ),

    // ── Cancelled ──────────────────────────────────────────────────────────
    OrderModel(
      id: 'o8',
      customerId: 'current_user',
      customerName: 'Sami Arab',
      providerId: 'p5',
      providerName: 'United Construction Co.',
      title: 'Exterior Wall Renovation',
      description: 'Renovate exterior wall, fix cracks, and repaint',
      area: 'Tiberias',
      selectedServiceId: 's15',
      selectedServiceName: 'Renovation',
      selectedServicePrice: 15000,
      serviceDate: DateTime.now().subtract(const Duration(days: 8)),
      status: OrderStatus.cancelled,
      priority: OrderPriority.normal,
      rejectReason: 'Appointment cancelled due to urgent circumstances',
      createdAt: DateTime.now().subtract(const Duration(days: 15)),
    ),
  ];

  static final List<ReviewModel> reviews = [
    ReviewModel(
      id: 'r1', orderId: 'o_old1', customerId: 'u1', customerName: 'Mohammed Salem',
      providerId: 'p1', speedRating: 5, qualityRating: 4.5, communicationRating: 5,
      comment: 'Excellent and fast work, highly recommended',
      relatedService: 'Electrical Installation',
      createdAt: DateTime.now().subtract(const Duration(days: 10)),
    ),
    ReviewModel(
      id: 'r2', orderId: 'o_old2', customerId: 'u2', customerName: 'Ahmad Khalil',
      providerId: 'p1', speedRating: 4, qualityRating: 5, communicationRating: 4.5,
      comment: 'High quality work, kept to the schedule',
      relatedService: 'Electrical Maintenance',
      createdAt: DateTime.now().subtract(const Duration(days: 20)),
    ),
    ReviewModel(
      id: 'r3', orderId: 'o_old3', customerId: 'u3', customerName: 'Sara Omar',
      providerId: 'p3', speedRating: 5, qualityRating: 5, communicationRating: 5,
      comment: 'Best plumber I have worked with, solved the problem quickly',
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
    ),
  ];

  static final UserModel currentUser = UserModel(
    id: 'current_user',
    fullName: 'Sami Arab',
    email: 'sami@example.com',
    phone: '0501111111',
    city: 'Nazareth',
    role: UserRole.customer,
  );
}